// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icyvbfrifydbipfssras.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljeXZiZnJpZnlkYmlwZnNzcmFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMzQ3NzEsImV4cCI6MjA2MDkxMDc3MX0.u6Es3yH5vC8KwOIpEdd9Y7LK9TTfr2F6LEDv4RGOCnc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);